### ISSUE TITLE
API키가 자동으로 넘어가지 않는 문제

### ISSUE THREAD

**Issue by bab2min** [Mo0nl19ht/youtube_crawler#3]
https://github.com/Mo0nl19ht/youtube_crawler/blob/3fc0d6c59f45542d0cc398e82b8097e0741b51ad/youtubecrawling/youtubecrawling.py#L212

이 부분이 `self.youtube = self.get_youtube(self.key_list[self.key_index]) `가 되어야 할듯 합니다.

**Comment by Mo0nl19ht** [comment]
아 감사합니다1!!!
주말에 고치겠습니다
